site_name: Thanatos

theme:
  name: material

plugins:
  - search
  - mkdocstrings
  - git-committers
  - git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: false
      htmlmin_opts:
          remove_comments: true
  - mermaid2
  - with-pdf:
      author: Pat McLean
      copyright: psmware ltd
      cover_subtitle: 'Codename: Thanatos  Î˜'
      toc_level: 2

markdown_extensions:
  - attr_list
  - admonition

nav:
  - Home: index.md
  - Getting Involved:
      - Contributing: contributing.md
      - Getting started: contributing/getting-started.md
      - Using the Repository: contributing/using-the-repo.md

