#  SPDX-License-Identifier: AGPL-3.0-only

#  Copyright (C) 2020-2021  Patrick McLean - psmware ltd

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
version: '3'

services:
  thanatos-app:
    image: thanatos-app
    container_name: thanatos-app
    hostname: thanatos-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.app
    user: vscode
    volumes:
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.gnupg:/home/vscode/.gnupg:cached
      - ..:/app:cached
    ports:
      - 0.0.0.0:3000:3000  # UI
      - 0.0.0.0:5000:5000  # API
      - 0.0.0.0:8000:8000  # Documentation
    env_file:
      - devcontainer.env
    depends_on:
      - thanatos-db

    command: sleep infinity

  thanatos-db:
    image: thanatos-db
    container_name: thanatos-db
    hostname: thanatos-db
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.db
    ports:
      - 5432:5432
    env_file:
      - devcontainer.env

  thanatos-dbadmin:
    image: thanatos-dbadmin
    container_name: thanatos-dbadmin
    hostname: thanatos-dbadmin
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dbadmin
    ports:
      - 0.0.0.0:5150:80
    env_file:
      - devcontainer.env
    depends_on:
      - thanatos-db